import time

from playwright.sync_api import expect
#testing 1233

class EndToEndUseCase:

    # constractor
    def __init__(self, page):
        self.page = page

    def end_to_end_use_case(self):
        expect(self.page.locator("//a[@href='/central-repository']//*[name()='svg']")).to_be_visible(timeout=50000)
        self.page.locator("//a[@href='/central-repository']//*[name()='svg']").click()
        expect(self.page.get_by_role("link", name="QA")).to_be_visible(timeout=50000)
        self.page.get_by_role("link", name="QA").click()
        expect(self.page.get_by_text("Add New Folder")).to_be_visible(timeout=50000)
        self.page.get_by_text("Add New Folder").click()
        expect(self.page.get_by_test_id("promptinputbox")).to_be_visible(timeout=50000)
        self.page.get_by_test_id("promptinputbox").fill("QA_Automation")
        expect(self.page.get_by_test_id("promptokbutton")).to_be_visible(timeout=50000)
        self.page.get_by_test_id("promptokbutton").click()
        expect(self.page.get_by_test_id("btn-click")).to_be_enabled(timeout=50000)
        self.page.get_by_test_id("btn-click").click()
        time.sleep(2)
        self.page.get_by_text("New Intent").click()
        expect(self.page.get_by_placeholder("Enter template title here")).to_be_enabled(timeout=50000)
        self.page.get_by_placeholder("Enter template title here").fill("test123")
        expect(self.page.locator(".questions-rich-text-area")).to_be_visible(timeout=50000)
        self.page.locator(".questions-rich-text-area").click()
        expect(self.page.locator(".questions-rich-text-area")).to_be_visible(timeout=50000)
        self.page.locator(".questions-rich-text-area").fill("What is PlayWright")
        expect(self.page.get_by_role("button", name="Add Cards")).to_be_visible(timeout=50000)
        self.page.get_by_role("button", name="Add Cards").click()
        expect(self.page.get_by_text("Text", exact=True)).to_be_visible(timeout=50000)
        self.page.get_by_text("Text", exact=True).click()
        time.sleep(1)
        self.page.locator("pre div").first.click()
        time.sleep(1)
        self.page.locator("pre div").first.fill("it is a Automation")
        time.sleep(1)
        # ///////////////
        expect(self.page.get_by_text("URL", exact=True)).to_be_visible(timeout=50000)
        self.page.get_by_text("URL", exact=True).click()
        expect(self.page.get_by_test_id("query-text")).to_be_visible(timeout=50000)
        self.page.get_by_test_id("query-text").locator("div").nth(2).click()
        expect(self.page.get_by_test_id("query-text")).to_be_visible(timeout=50000)
        self.page.get_by_test_id("query-text").locator("div").nth(2).fill(
            "https://videos.ctfassets.net/3viuren4us1n/212Id645FjXyX6ZOz9NJ1e/7a9d9727d3c13c5eb3cd9053a1e4a0fd/office-video.mp4")
        time.sleep(1)
        # expect(self.page.get_by_text("Shuffle", exact=True)).to_be_visible(timeout=50000)
        # self.page.get_by_text("Shuffle", exact=True).click()
        # time.sleep(2)
        # self.page.get_by_role("button", name="delete duplicate copy SHUFFLE").click()
        # expect(self.page.locator(".rich-text-textarea")).to_be_visible(timeout=50000)
        # self.page.locator(".rich-text-textarea").click()
        # expect(self.page.locator(".rich-text-textarea")).to_be_visible(timeout=50000)
        # self.page.locator(".rich-text-textarea").fill("test1")
        # expect(self.page.get_by_text("Image", exact=True)).to_be_visible(timeout=50000)
        # self.page.get_by_text("Image", exact=True).click()
        # expect(self.page.get_by_role("button", name="delete duplicate copy IMAGE")).to_be_visible(timeout=50000)
        # self.page.get_by_role("button", name="delete duplicate copy IMAGE").click()
        # expect(self.page.get_by_label("Upload Image")).to_be_visible(timeout=50000)
        # self.page.get_by_label("Upload Image").set_input_files("sad-sorry.gif")
        # expect(self.page.locator("#react-tabs-1")).to_be_visible(timeout=50000)
        # self.page.locator("#react-tabs-1").get_by_test_id("video").locator("i").click()
        # expect(self.page.get_by_placeholder("Enter video URL")).to_be_visible(timeout=50000)
        # self.page.get_by_placeholder("Enter video URL").click()
        # expect(self.page.get_by_placeholder("Enter video URL")).to_be_visible(timeout=50000)
        # self.page.get_by_placeholder("Enter video URL").fill(
        #     "https://videos.ctfassets.net/3viuren4us1n/212Id645FjXyX6ZOz9NJ1e/7a9d9727d3c13c5eb3cd9053a1e4a0fd/office-video.mp4")
        # expect(self.page.get_by_test_id("done-button")).to_be_visible(timeout=50000)
        # self.page.get_by_test_id("done-button").click()
        # expect(self.page.get_by_text("Carousel", exact=True)).to_be_visible(timeout=50000)
        # self.page.get_by_text("Carousel", exact=True).click()
        # expect(self.page.get_by_placeholder("Enter text here")).to_be_visible(timeout=50000)
        # self.page.get_by_placeholder("Enter text here").click()
        # expect(self.page.get_by_placeholder("Enter text here")).to_be_visible(timeout=50000)
        # self.page.get_by_placeholder("Enter text here").fill("test12")
        expect(self.page.locator("//*[@data-testid='feedback_ans_box']")).to_be_visible(timeout=50000)
        self.page.locator("//*[@data-testid='feedback_ans_box']").click()
        time.sleep(1)
        expect(self.page.locator("(//*[@class='react-switch-handle'])[2]")).to_be_visible(timeout=50000)
        self.page.locator("(//*[@class='react-switch-handle'])[2]").click()


        # ////////////////////
        self.page.get_by_role("button", name="Save").click()
        time.sleep(1)
        self.page.get_by_test_id("backbutton-btn").click()
        expect(self.page.locator("//a[@href='/chat-bot']//*[name()='svg']")).to_be_visible(timeout=50000)
        self.page.locator("//a[@href='/chat-bot']//*[name()='svg']").click()
        expect(self.page.get_by_role("heading", name="Transaction Bot MQA")).to_be_visible(timeout=50000)
        self.page.get_by_role("heading", name="Transaction Bot MQA").click()
        expect(self.page.get_by_text("Add New Folder")).to_be_visible(timeout=50000)
        self.page.get_by_text("Add New Folder").click()
        expect(self.page.get_by_test_id("promptinputbox")).to_be_visible(timeout=50000)
        self.page.get_by_test_id("promptinputbox").fill("QA_Automation")
        expect(self.page.get_by_test_id("promptokbutton")).to_be_visible(timeout=50000)
        self.page.get_by_test_id("promptokbutton").click()
        expect(self.page.get_by_test_id("chatbot-icon-btn")).to_be_visible(timeout=50000)
        self.page.get_by_test_id("chatbot-icon-btn").locator("img").nth(1).click()
        expect(self.page.get_by_text("Common")).to_be_visible(timeout=50000)
        self.page.get_by_text("Common").click()
        expect(self.page.locator("#react-select-6-option-8")).to_be_visible(timeout=50000)
        self.page.locator("#react-select-6-option-8").click()
        expect(self.page.get_by_test_id("import-popup-wrapper").get_by_text("QA_Automation")).to_be_visible(timeout=50000)
        self.page.get_by_test_id("import-popup-wrapper").get_by_text("QA_Automation").click()
        expect(self.page.get_by_role("listitem", name="test123")).to_be_visible(timeout=50000)
        self.page.get_by_role("listitem", name="test123").click()
        expect(self.page.get_by_role("button", name="Import")).to_be_visible(timeout=50000)
        self.page.get_by_role("button", name="Import").click()
        time.sleep(1)
        self.page.get_by_test_id("chatbot-icon-btn").locator("img").first.click()
        expect(self.page.locator("//div[text()=\"'Transaction Bot MQA' bot trained successfully\"]")).to_be_visible(timeout=50000)
        expect(self.page.get_by_label("Open Chat")).to_be_enabled()
        self.page.get_by_label("Open Chat").click()
        expect(self.page.locator("//span[@title='Transaction Bot MQA']")).to_be_visible()
        self.page.locator("//span[@title='Transaction Bot MQA']").click()
        self.page.get_by_placeholder("Ask me something").fill("What is PlayWright")
        self.page.locator("//button[@id='msgSenderButton']").click()
        time.sleep(2)
        print("The response for the question is ", self.page.locator("(//div[@class='rcw-wrapper-response'])[2]").text_content())
        expect(self.page.locator("//span[@class='rcw-options-icons cursor close-header']//img")).to_be_visible(timeout=50000)
        self.page.locator("//span[@class='rcw-options-icons cursor close-header']//img").click()
        self.page.locator("//button[normalize-space()='Skip']").click()
        self.page.locator("//button[normalize-space()='Close']").click()
        expect(self.page.locator("//a[@href='/analytics']//*[name()='svg']")).to_be_visible(timeout=50000)
        self.page.locator("//a[@href='/analytics']//*[name()='svg']").click()
        expect(self.page.locator("//span[@title='Refresh Dashboard']")).to_be_visible(timeout=50000)
        self.page.locator("//span[@title='Refresh Dashboard']").click()
        expect(self.page.locator("(//h3[@class='report-result'])[1]")).to_be_visible(timeout=50000)
        print("The Total count of conversion is ", self.page.locator("(//h3[@class='report-result'])[1]").text_content())

