#use this package to import autosuggestions
import time

from playwright.sync_api import Page, Playwright


def test_playwrightBasics(playwright: Playwright):
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    #context used stroe all cockies and caches in single file
    page = context.new_page()

    # Navigate to login page
    page.goto("https://mqa2.xavlab.xyz/")
    page.get_by_placeholder("Enter email").click()
    page.get_by_placeholder("Enter email").fill("puchha.pavan@telusinternational.com")
    page.get_by_role("button", name="Login").click()
    page.get_by_placeholder("Enter domain").click()
    page.get_by_placeholder("Enter domain").fill("xd")
    page.get_by_role("button", name="Login").click()
    page.get_by_placeholder("Enter password").click()
    page.get_by_placeholder("Enter password").fill("*Pavan@4331")
    page.get_by_role("button", name="Login").click()
    page.locator("li:nth-child(2) > a").click()
    page.get_by_role("heading", name="Transaction Bot MQA").click()
    time.sleep(3)
    # page.get_by_text("QA_Automation").click()
    # time.sleep(5)
    # page.locator("//span[@data-testid='checkbox-click']//input[@type='checkbox']").click()
    # time.sleep(5)
    # page.get_by_test_id("chatbot-icon-btn").locator("img").nth(2).click()
    # time.sleep(3)
    # page.get_by_test_id("btn-confirm-done").click()
    # time.sleep(3)
    page.locator("//span[contains(text(),'QA_Automation')]").click()
    time.sleep(2)
    page.locator("//span[contains(text(),'QA_Automation')]").hover()
    time.sleep(1)
    page.locator("(//span[@title='QA_Automation']/following::div/div[@class='icon-ellipsis-tree-show'])[1]").click()
    time.sleep(3)
    page.locator("//span[@title='QA_Automation']/following::div/div[@class='icon-ellipsis'])[1]").click()
    time.sleep(5)
    page.locator("//div[@id='simple-menu']//li[2]").hover()
    time.sleep(5)
    page.locator("//div[@id='simple-menu']//li[2]").click()


    # page.locator("//div[@class='icon-ellipsis-tree-show']").hover()
    # time.sleep(2)
    # page.locator("//div[@class='icon-ellipsis-tree-show']").click()
    # time.sleep(2)
    # page.locator("//div[contains(text(),'Delete')]").hover()
    # time.sleep(2)
    # page.locator("//div[contains(text(),'Delete')]").click()
    # time.sleep(2)
    # page.get_by_test_id("btn-confirm-done").click()
    # time.sleep(3)
    # page.locator("li:nth-child(4) > a").first.click()
    # time.sleep(3)
    # page.get_by_role("link", name="QA").click()
    # time.sleep(3)
    # page.get_by_text("QA_Automation").click()
    # time.sleep(3)
    # page.get_by_role("cell", name="test123").get_by_role("checkbox").check()
    # time.sleep(3)
    # page.get_by_role("button", name="Remove (1)").click()
    # time.sleep(3)
    # page.get_by_test_id("btn-confirm-done").click()
    # time.sleep(3)
    # page.locator(".icon-ellipsis-tree-show").click()
    # time.sleep(3)
    # page.locator("QA_Automation").click()
    # time.sleep(3)
    # page.locator("//div[@class='icon-ellipsis-tree-show']").hover()
    # time.sleep(2)
    # page.locator("//div[@class='icon-ellipsis-tree-show']").click()
    # time.sleep(2)
    # page.locator("//div[contains(text(),'Delete')]").hover()
    # time.sleep(2)
    # page.locator("//div[contains(text(),'Delete')]").click()
    # time.sleep(2)
    # page.get_by_test_id("btn-confirm-done").click()
    # time.sleep(3)
